name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

 steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
